name: digi_mom
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4
  path: ^1.8.0
  chewie: ^1.3.0
  video_player: ^2.6.1
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.2
  intl: ^0.18.1
  confetti: ^0.7.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/digi_mom_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/digi_mom_icon.png"

flutter_native_splash:
  image: assets/icons/digi_mom_icon.png
  color: "#B0E3C5"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/background/new.mp4
